- hosts: all
  tasks:
   - name: stop container
     shell: docker container stop mydockercontainer
   #- name: remove container
    # shell: docker container rm mydockercontainer
  # - name: remove docker image
   #  shell: docker image rmi prashanth6802/docker_image
   # - name: create new container
    # shell: docker container run -itd --name mydockercontainer -p 9000:80 prashanth6802/docker_image
